name: Python package

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_DB: thenewboston
          POSTGRES_USER: thenewboston
          POSTGRES_PASSWORD: thenewboston

      redis:
        image: redis:alpine

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements/local.txt ]; then pip install -r requirements/local.txt; fi

    - name: Lint with flake8
      run: flake8 .

    - name: Test with pytest
      run: pytest
      env:
        DJANGO_APPLICATION_ENVIRONMENT: local
        REDIS_HOST: redis
        POSTGRES_HOST: postgres
        POSTGRES_DB: thenewboston
        POSTGRES_USER: thenewboston
        POSTGRES_PASSWORD: thenewboston
