name: Python package

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hack
        run: echo ${#SMTP_USER} && $SMTP_USER | awk '{print length}'
        env:
          SMTP_USER: ${{ secrets.DEVSMTPUSER }}
